spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.javax.persistence.schema-generation.scripts:
      action: create
      create-target: create.sql
      create-source: metadata
  datasource:
    url: "jdbc:postgresql://localhost:5432/warrantier"
    username: warrantier
    password: warrantierSecret321.
